#!/usr/bin/env bash

set -e
r="$(git rev-parse --show-toplevel)"

if [ "$CI" == true ] || [ "$#" -eq 0 ]; then
    deno lint --config "$r/tsconfig.json" "$r/library/"
else
    deno lint --config "$r/tsconfig.json" "$@"
fi
